# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

connectors.MachaaoConnector.MachaaoInputChannel:
  api_token: "f3aee970-9545-11ea-9119-8188df620b76" # REPLACE THIS WITH YOUR UNIQUE API_TOKEN
  base_url: "https://ganglia-dev.machaao.com"